#!/bin/sh
#
# MOTD update script for livepatch-client.
#
if [ ! -f "/snap/bin/canonical-livepatch" ]; then
    exit 0
fi
msg=$(/snap/bin/canonical-livepatch kernel-upgrade-required 2> /dev/null)
code=$?
if [ $code -eq 0 ] || [ $code -eq 1 ]; then
    echo "$msg"
    echo
fi
